<template>
	<div>
		<ILayout>
			<ILayoutHeader>
				<navbar></navbar>
			</ILayoutHeader>
			<ILayoutContent>
				<NuxtPage></NuxtPage>
			</ILayoutContent>
			<ILayoutFooter>
				footer
			</ILayoutFooter>
		</ILayout>
	</div>
</template>
